### ISSUE TITLE
[sbt plugin] Configure custom configuration automatically

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scala-debug-adapter#267]
Currently, custom configurations must be configured manually with one of these settings:
```scala
inConfig(CustomConfig)(DebugAdapterPlugin.runSettings)
inConfig(CustomConfig)(DebugAdapterPlugin.testSettings)
```

Otherwise, it is not possible to run/debug the main classes and the tests of these configuration.

For example this is how to configure the debugger for the `IntegrationTest` config:
```scala
lazy val root = (project in file(".")).
configs(IntegrationTest)
  .settings(
    Defaults.itSettings,
    inConfig(IntegrationTest)(DebugAdapterPlugin.testSettings), // configure the debugger for IntegrationTest 
    ...
  )
```

To improve this we can try to use the `onLoad` setting in sbt and configure the debugger automatically.

**Comment by slovvik** [comment]
I have checked the workaround (in vs code) and it seems to work only for the build-in configurations.

**Comment by slovvik** [comment]
@adpi2 could you give me some hints on how to implement it? I could give it a try if you want.

**Comment by adpi2** [comment]
For a custom configuration with a `run` task, this should work:
```scala
val CustomConfig = Configuration.of("CustomConfig", "custom-config")

val root = project.in(file("."))
  .configs(CustomConfig)
  .settings(
    inConfig(CustomConfig)(Defaults.compileSettings ++ DebugAdapterPlugin.runSettings),
  )
```

For a custom config with a `test` task, it should be:
```scala
val CustomConfig = Configuration.of("CustomConfig", "custom-config")

val root = project.in(file("."))
  .configs(CustomConfig)
  .settings(
    inConfig(CustomConfig)(Defaults.testSettings ++ DebugAdapterPlugin.testSettings),
  )
```

If that does not work, we would be better to fix it before we implement automated configuration.
@slovvik  Could you try that and tell me if you have any trouble, and what kind of trouble?

**Comment by slovvik** [comment]
Well, I do not know how to really test it so I have tried in vscode. This is my configuration:
```scala
// lazy val SystemTest = config("system") extend(Test)
val SystemTest = Configuration.of("System", "system")

lazy val root = (project in file("."))
.configs(IntegrationTest, SystemTest)
  .settings(
    Defaults.itSettings,
    inConfig(SystemTest)(Defaults.testSettings ++ DebugAdapterPlugin.testSettings)
  )

libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.9" % Test
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.9" % IntegrationTest
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.9" % SystemTest
```
I tried both `config` method and `.of` method as it says in the comments that `.of` should be not used.
In both cases I got
```
[Error - 11:04:11 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  BuildTargetIdentifier(file:/Users/b.slowik/VsCodeProjects/scalatest-example3/#root/System) is not a valid build target
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  BuildTargetIdentifier(file:/Users/b.slowik/VsCodeProjects/scalatest-example3/#root/System) is not a valid build target
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.$anonfun$applyOrElse$4(BuildServerConnection.scala:300)
	at scala.Option.getOrElse(Option.scala:201)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:298)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:286)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	... 3 more
```
Here is the project directory structure
![image](https://user-images.githubusercontent.com/12632638/184608527-8865a423-da22-4b1e-8a3c-c74f6324fbb2.png)

**Comment by adpi2** [comment]
Thanks @slovvik, I will try to understand what's happening here.

**Comment by slovvik** [comment]
@adpi2 any update? I could help, but I would need some help also :)

**Comment by adpi2** [comment]
Closing as no longer relevant considering [the direction that sbt is taking](https://eed3si9n.com/sbt-drop-custom-config)
