### ISSUE TITLE
Garbage collected element

### ISSUE THREAD

**Issue by iusildra** [scalacenter/scala-debug-adapter#473]
According to [this CI run](https://github.com/scalacenter/scala-debug-adapter/actions/runs/5314112345/jobs/9719534757?pr=456), it seems that one element has been garbage collection

**Comment by adpi2** [comment]
For reference, here is the test failure:
```
[error] ==> X ch.epfl.scala.debugadapter.Scala212EvaluationTests.evaluate type parameter list and multi parameter lists  12.454s java.lang.NullPointerException: null
[error]     at ch.epfl.scala.debugadapter.testfmk.DebugTest.$anonfun$check$4(DebugTestSuite.scala:112)
[error]     at ch.epfl.scala.debugadapter.testfmk.DebugTest.$anonfun$check$4$adapted(DebugTestSuite.scala:105)
[error]     at scala.collection.immutable.Map$Map1.foreach(Map.scala:193)
[error]     at ch.epfl.scala.debugadapter.testfmk.DebugTest.check(DebugTestSuite.scala:105)
[error]     at ch.epfl.scala.debugadapter.testfmk.DebugTest.check(DebugTestSuite.scala:76)
[error]     at ch.epfl.scala.debugadapter.testfmk.DebugTest.check$(DebugTestSuite.scala:71)
[error]     at ch.epfl.scala.debugadapter.testfmk.DebugTestSuite.check(DebugTestSuite.scala:20)
[error]     at ch.epfl.scala.debugadapter.ScalaEvaluationTests.$anonfun$new$106(ScalaEvaluationTests.scala:1154)
```

This is quite unexpected but not a garbage collected element. The program has not even started.
